package consts

const WrongUsernameOrPassword = "Wrong username or password"
const WrongPassword = "Wrong password"
const InternalErrorMessage = "Something went wrong on our end, please try again"
const UserAlreadyExists = "User with the given email address or username already exists"
const UserDoesNotExist = "User does not exist"
const NotFriends = "You are not friend with this person"
const AlreadyFriends = "You are already friend with this person"
const NotOwner = "You are not owner of this group"
const NotInGroup = "You are not part of this group"
const Provide = "You have to provide "
const ProvideGroupId = Provide + "group id"
const ProvideGroupIdAndUserId = Provide + "group id and user id"
const ProvideFriendId = Provide + "friend id"
const UserInGroup = "User is already a member of this group"
